import type { Group } from "three";
import { createTeaCup, createTeapot, createPineappleCake, createBubbleTea } from "./tea-food";
import { createRedLantern, createSkyLantern, createUmbrella, createTemplePouch } from "./crafts";
import { createRailTicket, createForestTrain, createFlipFlops, createMarketBag } from "./travel-objects";
import { createDumplingSteamer, createBeefNoodles, createMangoIce, createOolongTin } from "./food-series-two";
import { createJadePendant, createOcarina, createBambooFan, createFloralPurse } from "./craft-series-two";
import { createTaipeiTower, createScooter, createCamera, createPostcards } from "./travel-series-two";

import { createPapayaMilk, createWinterMelonTea, createColdOolong, createPlumJuice } from "./drinks-series-three";
import { createGuaBao, createTaroBowl, createOysterOmelette, createScallionPancake } from "./food-series-three";
import { createMemorialHall, createFortSanDomingo, createQueensHead, createLongshanGate } from "./landmarks-series-three";

import { createCeramicWindBell, createWovenFishCharm, createChineseKnot, createBambooChime } from "./hanging-crafts";
import { createTaiwanIslandCharm, createMiniLanternCharm, createTaiwanBlackBearCharm } from "./hanging-keepsakes";

export interface Souvenir {
  id: string;
  name: string;
  chineseName: string;
  origin: string;
  description: string;
  details: string[];
  hanging?: boolean;
  create: () => Group;
}

export const souvenirs: Souvenir[] = [
  { id: "yingge-tea-cup", name: "A moment of tea", chineseName: "茶杯", origin: "Yingge · ceramics", description: "Blue blossoms on porcelain. A small invitation to slow down.", details: ["Hollow porcelain body", "Cobalt botanical decoration", "Glazed rim and tea surface"], create: createTeaCup },
  { id: "gongfu-teapot", name: "The patient pour", chineseName: "茶壺", origin: "Taiwan · tea culture", description: "A little clay pot, made for the ritual of another cup.", details: ["Sculpted clay profile", "Curved spout and loop handle", "Separate lid and maker’s details"], create: createTeapot },
  { id: "pineapple-cake", name: "Something sweet", chineseName: "鳳梨酥", origin: "Taiwan · bakery keepsakes", description: "Golden pastry, pineapple filling, and a gift worth bringing home.", details: ["Porous baked crust", "Exposed pineapple filling", "Folded gift wrapper"], create: createPineappleCake },
  { id: "bubble-tea", name: "An afternoon treat", chineseName: "珍珠奶茶", origin: "Taiwan · street drinks", description: "Milk tea and glossy pearls. A familiar companion for a wandering afternoon.", details: ["Translucent cup", "Individual tapioca pearls", "Sealed lid and wide straw"], create: createBubbleTea },
  { id: "jiufen-lantern", name: "A street after dark", chineseName: "紅燈籠", origin: "Jiufen · evening streets", description: "Red paper and warm light, remembered from a narrow hillside lane.", details: ["Ribbed paper shade", "Gold fittings", "Cord and individual tassel strands"], create: createRedLantern },
  { id: "pingxi-sky-lantern", name: "A wish in the sky", chineseName: "天燈", origin: "Pingxi · lantern traditions", description: "A paper keepsake carrying a wish for peace and happiness.", details: ["Shaped paper panels", "Printed wishes", "Open bamboo base"], create: createSkyLantern },
  { id: "meinong-umbrella", name: "Shelter in bloom", chineseName: "油紙傘", origin: "Meinong · Hakka craft", description: "Painted flowers spread across an oil-paper canopy.", details: ["Painted radial canopy", "Exposed bamboo spokes", "Wooden shaft and handle"], create: createUmbrella },
  { id: "temple-pouch", name: "Keep a little peace", chineseName: "平安袋", origin: "Taiwan · temple keepsakes", description: "A small red pouch inspired by embroidered keepsakes carried close.", details: ["Brocade fabric", "Gold embroidery", "Braided cord and tassel"], create: createTemplePouch },
  { id: "rail-ticket", name: "Somewhere by rail", chineseName: "火車票", origin: "Taipei · rail journeys", description: "A souvenir ticket for the pleasure of watching the city give way to hills.", details: ["Curved paper stock", "Original reproduction typography", "Punched detail and worn edges"], create: createRailTicket },
  { id: "alishan-train", name: "Into the mountain", chineseName: "阿里山小火車", origin: "Alishan · forest railway", description: "A red miniature recalling a slow journey through the forest.", details: ["Locomotive body and glazing", "Detailed wheels and running gear", "Rail and sleeper display base"], create: createForestTrain },
  { id: "blue-flip-flops", name: "Take the easy way", chineseName: "藍白拖", origin: "Taiwan · everyday life", description: "Blue soles and white straps. An everyday object with a place in the story.", details: ["Shaped rubber soles", "Textured footbeds", "White Y straps"], create: createFlipFlops },
  { id: "market-bag", name: "A morning at the market", chineseName: "茄芷袋", origin: "Taiwan · market culture", description: "Bright woven stripes, ready for whatever you find along the way.", details: ["Open woven body", "Traditional striped palette", "Handles and stitched seams"], create: createMarketBag },
  { id: "dumpling-steamer", name: "One more dumpling", chineseName: "小籠包", origin: "Taipei · shared tables", description: "Lift the bamboo lid. A few delicate folds hold the warmth of a shared meal.", details: ["Bamboo basket and woven base", "Sculpted dumpling pleats", "Paper lining"], create: createDumplingSteamer },
  { id: "beef-noodles", name: "A bowl to come back to", chineseName: "牛肉麵", origin: "Taipei · noodle shops", description: "Rich broth, winding noodles, and the comfort of finding a favorite little shop.", details: ["Hollow ceramic bowl", "Individual noodles and toppings", "Chopsticks and glazed broth"], create: createBeefNoodles },
  { id: "mango-ice", name: "Summer, by the spoonful", chineseName: "芒果冰", origin: "Taiwan · summer afternoons", description: "Golden mango over a mountain of ice. A bright pause in the heat.", details: ["Textured shaved-ice mound", "Separate mango pieces", "Condensed milk accents"], create: createMangoIce },
  { id: "oolong-tin", name: "Bring the mountains home", chineseName: "烏龍茶罐", origin: "Taiwan · high mountain tea", description: "A little tin of oolong, with a landscape you can remember each time you open it.", details: ["Rolled metal rims and fitted lid", "Original mountain illustration", "Loose tea leaves"], create: createOolongTin },
  { id: "jade-pendant", name: "Something to carry close", chineseName: "玉墜", origin: "Taiwan · decorative keepsakes", description: "A cool green circle on a red cord. A small object to carry through the day.", details: ["Polished stone with central opening", "Subtle jade mottling", "Knotted cord and bead"], create: createJadePendant },
  { id: "yingge-ocarina", name: "A tune from the pottery town", chineseName: "陶笛", origin: "Yingge · ceramic craft", description: "A pocket-sized ceramic instrument, ready for a melody of your own.", details: ["Sculpted ceramic body", "Finger holes and mouthpiece", "Celadon glaze"], create: createOcarina },
  { id: "bamboo-fan", name: "A little mountain breeze", chineseName: "竹扇", origin: "Taiwan · craft keepsakes", description: "An unfolding landscape, held between paper and bamboo.", details: ["Pleated painted paper", "Individual bamboo ribs", "Metal pivot"], create: createBambooFan },
  { id: "floral-purse", name: "Flowers for the journey", chineseName: "花布小袋", origin: "Taiwan · flower cloth", description: "Bright blossoms on a small fabric pouch, with room for the things you keep finding.", details: ["Original floral textile", "Inflated fabric and seam stitching", "Zipper teeth and pull"], create: createFloralPurse },
  { id: "taipei-tower", name: "Look up, then wander", chineseName: "台北101", origin: "Taipei · city skyline", description: "A small piece of the skyline, recalling the moment the city first felt enormous.", details: ["Eight flared tower sections", "Window grids and architectural trims", "Crown, spire, and stepped base"], create: createTaipeiTower },
  { id: "city-scooter", name: "The city in motion", chineseName: "機車", origin: "Taiwan · everyday streets", description: "A little scooter inspired by the rhythm of everyday city streets.", details: ["Rounded body and padded seat", "Detailed wheels and fork", "Lights, mirrors, and handlebars"], create: createScooter },
  { id: "travel-camera", name: "Keep this frame", chineseName: "底片相機", origin: "Taiwan · travel memories", description: "A familiar film camera for the alley, the mountains, and the moment in between.", details: ["Brushed metal and textured leather", "Layered lens and glass", "Dials, viewfinder, and strap fittings"], create: createCamera },
  { id: "taiwan-postcards", name: "Wish you were here", chineseName: "明信片", origin: "Taiwan · letters home", description: "Paper landscapes, ready for a few words about somewhere you want to remember.", details: ["Original Taiwan landscape illustrations", "Curved paper and layered edges", "Souvenir stamp and postal details"], create: createPostcards },
  { id: "papaya-milk", name: "A sunny little sip", chineseName: "木瓜牛奶", origin: "Taiwan · juice stalls", description: "Peach-colored papaya milk, served with a slice of sunshine.", details: ["Printed retro glass and creamy foam", "Papaya wedge with individual seeds", "Textured cork coaster"], create: createPapayaMilk },
  { id: "winter-melon-tea", name: "Cool down, keep wandering", chineseName: "冬瓜茶", origin: "Taiwan · street drinks", description: "Amber winter melon tea and ice, ready for a warm afternoon walk.", details: ["Hollow translucent cup", "Separate ice cubes and straw", "Original illustrated drink label"], create: createWinterMelonTea },
  { id: "cold-oolong", name: "Mountains in a bottle", chineseName: "冷泡烏龍", origin: "Taiwan · tea culture", description: "Cold-brewed oolong with a small cup for a quiet pause.", details: ["Glass bottle with ridged screw cap", "Original mountain label", "Ceramic tasting cup"], create: createColdOolong },
  { id: "plum-juice", name: "A sweet and sour afternoon", chineseName: "酸梅湯", origin: "Taiwan · summer drinks", description: "Deep plum juice, a little citrus, and the clink of ice in a ribbed glass.", details: ["Fluted glass and translucent juice", "Individual ice cubes", "Dried plums and citrus garnish"], create: createPlumJuice },
  { id: "gua-bao", name: "A bun full of stories", chineseName: "刈包", origin: "Taiwan · street food", description: "A soft folded bun holding pork, pickled greens, and a scattering of peanuts.", details: ["Sculpted folded bun", "Separate pork and fat layers", "Peanuts, pickles, and coriander"], create: createGuaBao },
  { id: "taro-bowl", name: "Meet me at the dessert shop", chineseName: "芋圓", origin: "Jiufen · sweet pauses", description: "Purple taro, golden sweet potato, and red beans in a little bowl of syrup.", details: ["Hollow glazed ceramic bowl", "Individual taro and sweet potato pieces", "Red beans and metal spoon"], create: createTaroBowl },
  { id: "oyster-omelette", name: "One more night-market stop", chineseName: "蚵仔煎", origin: "Taiwan · night markets", description: "Golden egg, oysters, and a glossy ribbon of sauce, fresh from the stall.", details: ["Irregular browned egg surface", "Sculpted oysters and leafy greens", "Starch patches and sauce ribbons"], create: createOysterOmelette },
  { id: "scallion-pancake", name: "Follow the smell of the griddle", chineseName: "蔥油餅", origin: "Taiwan · street kitchens", description: "Crisp golden wedges, with flaky layers and bright green scallions tucked inside.", details: ["Six separate cut wedges", "Layered pastry edges", "Browned surface, scallions, and crumbs"], create: createScallionPancake },
  { id: "memorial-hall", name: "Under the blue roof", chineseName: "中正紀念堂", origin: "Taipei · landmark walks", description: "White stone and blue octagonal roofs, remembered from a broad city square.", details: ["Curved double octagonal roofs", "Stepped podium and staircase", "Arched entrance and gold finial"], create: createMemorialHall },
  { id: "fort-san-domingo", name: "Red walls by the river", chineseName: "紅毛城", origin: "Tamsui · riverside history", description: "A red fort miniature recalling an afternoon above the Tamsui River.", details: ["Locally drawn weathered brickwork", "Arched openings and window bars", "Crenellations and corner towers"], create: createFortSanDomingo },
  { id: "queens-head", name: "A shape made by the sea", chineseName: "女王頭", origin: "Yehliu · coastal landscapes", description: "A slender sandstone silhouette, shaped by time, wind, and the sea.", details: ["Asymmetric sculpted crown and neck", "Honeycomb sandstone texture", "Irregular rocky display base"], create: createQueensHead },
  { id: "longshan-gate", name: "Pause at the temple gate", chineseName: "龍山寺", origin: "Taipei · temple architecture", description: "A miniature gate inspired by Longshan Temple’s layered roofs and ornamental craft.", details: ["Curved tile roofs and red columns", "Paired ridge dragons and brackets", "Original Chinese name board"], create: createLongshanGate },
  { id: "ceramic-wind-bell", name: "A breeze from the pottery town", chineseName: "陶瓷風鈴", origin: "Yingge · ceramic keepsakes", description: "A glazed bell, a small clapper, and a paper tail waiting for a passing breeze.", details: ["Hollow decorated porcelain bell", "Suspension cord and internal clapper", "Dangling paper windcatcher"], hanging: true, create: createCeramicWindBell },
  { id: "woven-fish-charm", name: "Carry a little abundance", chineseName: "編織魚吊飾", origin: "Taiwan · woven craft inspiration", description: "A little woven fish with bright threads and a tassel, made to keep you company.", details: ["Textured woven body and sculpted fins", "Detailed eyes and tail", "Hanging loop and strand tassel"], hanging: true, create: createWovenFishCharm },
  { id: "chinese-knot", name: "A knot for the journey", chineseName: "中國結", origin: "Taiwan · decorative knot craft", description: "Red cords cross and curl into a keepsake of good wishes.", details: ["Interwoven three-dimensional cords", "Gold bead and hanging loop", "Individual tassel strands"], hanging: true, create: createChineseKnot },
  { id: "bamboo-chime", name: "Bring a little breeze home", chineseName: "竹風鈴", origin: "Taiwan · bamboo craft inspiration", description: "Five bamboo tubes hang beneath a wooden canopy, with a little catcher below.", details: ["Hollow bamboo tubes of different lengths", "Canopy and suspension cords", "Central clapper and windcatcher"], hanging: true, create: createBambooChime },
  { id: "taiwan-island-charm", name: "An island to carry close", chineseName: "台灣吊墜", origin: "Taiwan · island memories", description: "A jade-colored island, with a golden coast and little mountains to remember.", details: ["Thick island silhouette", "Gold edge and raised mountain details", "Metal bail, red cord, and tassel"], hanging: true, create: createTaiwanIslandCharm },
  { id: "mini-lantern-charm", name: "A little light for the road", chineseName: "小燈籠吊飾", origin: "Taiwan · lantern keepsakes", description: "A tiny framed lantern with botanical paper panels, suspended on a red cord.", details: ["Hexagonal frame and decorated paper panels", "Detailed roof and open bottom", "Hanging loop and tassel"], hanging: true, create: createMiniLanternCharm },
  { id: "taiwan-black-bear-charm", name: "A mountain friend", chineseName: "台灣黑熊吊飾", origin: "Taiwan · wildlife inspiration", description: "A small black bear keepsake with the familiar pale V across its chest.", details: ["Sculpted ears, muzzle, and paws", "Raised cream V chest marking", "Brass bail and cord loop"], hanging: true, create: createTaiwanBlackBearCharm },
];
