export interface SouvenirMetadata {
  id: string;
  label: string;
  description: string;
  kind: string;
  invitation: string;
  tags: string[];
}

// Plain metadata shared by the tabletop and journey engine; no rendering dependencies.
export const souvenirCatalog: SouvenirMetadata[] = [
  {"id": "yingge-tea-cup", "label": "A moment of tea", "description": "Blue blossoms on porcelain. A small invitation to slow down.", "kind": "tea", "invitation": "What would you like to slow down for?", "tags": ["Ritual", "Pause", "Craft"]},
  {"id": "gongfu-teapot", "label": "The patient pour", "description": "A little clay pot, made for the ritual of another cup.", "kind": "tea", "invitation": "Who would you share another cup with?", "tags": ["Ritual", "Patience", "Togetherness"]},
  {"id": "pineapple-cake", "label": "Something sweet", "description": "Golden pastry, pineapple filling, and a gift worth bringing home.", "kind": "noodles", "invitation": "Who would you bring a little sweetness home to?", "tags": ["Taste", "Giving", "Home"]},
  {"id": "bubble-tea", "label": "An afternoon treat", "description": "Milk tea and glossy pearls. A familiar companion for a wandering afternoon.", "kind": "noodles", "invitation": "What would make a wandering afternoon yours?", "tags": ["Taste", "Wandering", "Everyday"]},
  {"id": "jiufen-lantern", "label": "A street after dark", "description": "Red paper and warm light, remembered from a narrow hillside lane.", "kind": "lantern", "invitation": "Where could a little warm light lead you?", "tags": ["Evening", "Wandering", "Light"]},
  {"id": "pingxi-sky-lantern", "label": "A wish in the sky", "description": "A paper keepsake carrying a wish for peace and happiness.", "kind": "lantern", "invitation": "What wish would you carry into this journey?", "tags": ["Hope", "Ritual", "Light"]},
  {"id": "meinong-umbrella", "label": "Shelter in bloom", "description": "Painted flowers spread across an oil-paper canopy.", "kind": "umbrella", "invitation": "What does finding a little shelter mean to you?", "tags": ["Shelter", "Craft", "Flowers"]},
  {"id": "temple-pouch", "label": "Keep a little peace", "description": "A small red pouch inspired by embroidered keepsakes carried close.", "kind": "charm", "invitation": "What would you like to keep close?", "tags": ["Ritual", "Hope", "Peace"]},
  {"id": "rail-ticket", "label": "Somewhere by rail", "description": "A souvenir ticket for the pleasure of watching the city give way to hills.", "kind": "ticket", "invitation": "What is waiting beyond the city?", "tags": ["Movement", "Possibility", "Landscape"]},
  {"id": "alishan-train", "label": "Into the mountain", "description": "A red miniature recalling a slow journey through the forest.", "kind": "ticket", "invitation": "What would you notice on a slower journey?", "tags": ["Movement", "Forest", "Slow"]},
  {"id": "blue-flip-flops", "label": "Take the easy way", "description": "Blue soles and white straps. An everyday object with a place in the story.", "kind": "walk", "invitation": "What happens when you take the easy way?", "tags": ["Everyday", "Freedom", "Walking"]},
  {"id": "market-bag", "label": "A morning at the market", "description": "Bright woven stripes, ready for whatever you find along the way.", "kind": "bag", "invitation": "What would you want to find along the way?", "tags": ["Market", "Discovery", "Everyday"]},
  {"id": "dumpling-steamer", "label": "One more dumpling", "description": "Lift the bamboo lid. A few delicate folds hold the warmth of a shared meal.", "kind": "noodles", "invitation": "Who would you make room for at the table?", "tags": ["Taste", "Togetherness", "Warmth"]},
  {"id": "beef-noodles", "label": "A bowl to come back to", "description": "Rich broth, winding noodles, and the comfort of finding a favorite little shop.", "kind": "noodles", "invitation": "What makes a little place worth coming back to?", "tags": ["Taste", "Comfort", "Ritual"]},
  {"id": "mango-ice", "label": "Summer, by the spoonful", "description": "Golden mango over a mountain of ice. A bright pause in the heat.", "kind": "noodles", "invitation": "What would a bright afternoon pause feel like?", "tags": ["Taste", "Summer", "Pause"]},
  {"id": "oolong-tin", "label": "Bring the mountains home", "description": "A little tin of oolong, with a landscape you can remember each time you open it.", "kind": "tea", "invitation": "What would you like to bring home in a little ritual?", "tags": ["Ritual", "Landscape", "Home"]},
  {"id": "jade-pendant", "label": "Something to carry close", "description": "A cool green circle on a red cord. A small object to carry through the day.", "kind": "charm", "invitation": "What makes an object feel personal to you?", "tags": ["Connection", "Craft", "Keepsake"]},
  {"id": "yingge-ocarina", "label": "A tune from the pottery town", "description": "A pocket-sized ceramic instrument, ready for a melody of your own.", "kind": "record", "invitation": "What sound would you give this journey?", "tags": ["Sound", "Play", "Craft"]},
  {"id": "bamboo-fan", "label": "A little mountain breeze", "description": "An unfolding landscape, held between paper and bamboo.", "kind": "mountain", "invitation": "What landscape would you keep in your hand?", "tags": ["Landscape", "Craft", "Pause"]},
  {"id": "floral-purse", "label": "Flowers for the journey", "description": "Bright blossoms on a small fabric pouch, with room for the things you keep finding.", "kind": "charm", "invitation": "Which little things would you carry with you?", "tags": ["Flowers", "Keepsake", "Craft"]},
  {"id": "taipei-tower", "label": "Look up, then wander", "description": "A small piece of the skyline, recalling the moment the city first felt enormous.", "kind": "city", "invitation": "What makes a new city feel full of possibility?", "tags": ["City", "Wonder", "Discovery"]},
  {"id": "city-scooter", "label": "The city in motion", "description": "A little scooter inspired by the rhythm of everyday city streets.", "kind": "bicycle", "invitation": "How would you find your own rhythm in the city?", "tags": ["Movement", "Everyday", "Freedom"]},
  {"id": "travel-camera", "label": "Keep this frame", "description": "A familiar film camera for the alley, the mountains, and the moment in between.", "kind": "camera", "invitation": "What small detail would you want to keep?", "tags": ["Noticing", "Memory", "Discovery"]},
  {"id": "taiwan-postcards", "label": "Wish you were here", "description": "Paper landscapes, ready for a few words about somewhere you want to remember.", "kind": "book", "invitation": "Who would you write to, and what would you say?", "tags": ["Words", "Connection", "Memory"]},
  {"id": "papaya-milk", "label": "A sunny little sip", "description": "Peach-colored papaya milk, served with a slice of sunshine.", "kind": "noodles", "invitation": "What little taste would brighten your afternoon?", "tags": ["Taste", "Summer", "Everyday"]},
  {"id": "winter-melon-tea", "label": "Cool down, keep wandering", "description": "Amber winter melon tea and ice, ready for a warm afternoon walk.", "kind": "tea", "invitation": "Where would you wander after a cooling pause?", "tags": ["Taste", "Pause", "Wandering"]},
  {"id": "cold-oolong", "label": "Mountains in a bottle", "description": "Cold-brewed oolong with a small cup for a quiet pause.", "kind": "tea", "invitation": "What would you notice over a quiet cup?", "tags": ["Ritual", "Landscape", "Pause"]},
  {"id": "plum-juice", "label": "A sweet and sour afternoon", "description": "Deep plum juice, a little citrus, and the clink of ice in a ribbed glass.", "kind": "noodles", "invitation": "What taste brings a summer afternoon back?", "tags": ["Taste", "Summer", "Memory"]},
  {"id": "gua-bao", "label": "A bun full of stories", "description": "A soft folded bun holding pork, pickled greens, and a scattering of peanuts.", "kind": "noodles", "invitation": "What would you discover by following your appetite?", "tags": ["Taste", "Street food", "Discovery"]},
  {"id": "taro-bowl", "label": "Meet me at the dessert shop", "description": "Purple taro, golden sweet potato, and red beans in a little bowl of syrup.", "kind": "noodles", "invitation": "Who would you meet for a little sweet pause?", "tags": ["Taste", "Togetherness", "Pause"]},
  {"id": "oyster-omelette", "label": "One more night-market stop", "description": "Golden egg, oysters, and a glossy ribbon of sauce, fresh from the stall.", "kind": "noodles", "invitation": "What would make you stop at one more stall?", "tags": ["Taste", "Evening", "Energy"]},
  {"id": "scallion-pancake", "label": "Follow the smell of the griddle", "description": "Crisp golden wedges, with flaky layers and bright green scallions tucked inside.", "kind": "noodles", "invitation": "Where could the smell of a street kitchen lead you?", "tags": ["Taste", "Wandering", "Everyday"]},
  {"id": "memorial-hall", "label": "Under the blue roof", "description": "White stone and blue octagonal roofs, remembered from a broad city square.", "kind": "city", "invitation": "What catches your attention when a city opens into a square?", "tags": ["City", "Architecture", "History"]},
  {"id": "fort-san-domingo", "label": "Red walls by the river", "description": "A red fort miniature recalling an afternoon above the Tamsui River.", "kind": "city", "invitation": "What stories might you find beside the river?", "tags": ["History", "River", "Discovery"]},
  {"id": "queens-head", "label": "A shape made by the sea", "description": "A slender sandstone silhouette, shaped by time, wind, and the sea.", "kind": "mountain", "invitation": "What shape in the landscape would stay with you?", "tags": ["Nature", "Coast", "Wonder"]},
  {"id": "longshan-gate", "label": "Pause at the temple gate", "description": "A miniature gate inspired by Longshan Temple’s layered roofs and ornamental craft.", "kind": "charm", "invitation": "What would you pause to notice at the temple gate?", "tags": ["Ritual", "Architecture", "Craft"]},
  {"id": "ceramic-wind-bell", "label": "A breeze from the pottery town", "description": "A glazed bell, a small clapper, and a paper tail waiting for a passing breeze.", "kind": "record", "invitation": "What sound would bring the journey back?", "tags": ["Sound", "Craft", "Memory"]},
  {"id": "woven-fish-charm", "label": "Carry a little abundance", "description": "A little woven fish with bright threads and a tassel, made to keep you company.", "kind": "charm", "invitation": "What little wish would you carry?", "tags": ["Craft", "Hope", "Keepsake"]},
  {"id": "chinese-knot", "label": "A knot for the journey", "description": "Red cords cross and curl into a keepsake of good wishes.", "kind": "charm", "invitation": "Who would you carry a good wish for?", "tags": ["Connection", "Hope", "Craft"]},
  {"id": "bamboo-chime", "label": "Bring a little breeze home", "description": "Five bamboo tubes hang beneath a wooden canopy, with a little catcher below.", "kind": "record", "invitation": "Where would you stop to listen?", "tags": ["Sound", "Nature", "Pause"]},
  {"id": "taiwan-island-charm", "label": "An island to carry close", "description": "A jade-colored island, with a golden coast and little mountains to remember.", "kind": "mountain", "invitation": "Which part of the island stays with you?", "tags": ["Landscape", "Memory", "Keepsake"]},
  {"id": "mini-lantern-charm", "label": "A little light for the road", "description": "A tiny framed lantern with botanical paper panels, suspended on a red cord.", "kind": "lantern", "invitation": "What little light would you keep close?", "tags": ["Light", "Hope", "Keepsake"]},
  {"id": "taiwan-black-bear-charm", "label": "A mountain friend", "description": "A small black bear keepsake with the familiar pale V across its chest.", "kind": "charm", "invitation": "What would draw you toward the mountains?", "tags": ["Nature", "Play", "Keepsake"]},
];
